---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: swiggy
spec:
  containers:
    - name: cont3
      image: venkat2708/train-ticket-booking:v2
      ports:
        - containerPort: 80
